
package quizapp.ui.admin;

import javax.swing.JOptionPane;
import models.Question;
import repositories.QuestionRepository;
import services.QuestionService;

/**
 *
 * @author x
 */
public class AddQuestion extends javax.swing.JFrame {

    /**
     * Creates new form AddQuestion
     */
    private final QuestionService questionService;

    public AddQuestion() {
        initComponents();
        this.questionService = new QuestionRepository();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        optionD = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        question = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        optionA = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        optionB = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        optionC = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        answer = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        background.setForeground(new java.awt.Color(102, 255, 51));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizapp/ui/admin/addStudent-page.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(384, 800));

        jPanel1.setMaximumSize(new java.awt.Dimension(384, 800));
        jPanel1.setMinimumSize(new java.awt.Dimension(384, 800));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ADD QUESTION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(520, 10, 200, 40);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(D)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 430, 20, 40);

        optionD.setBackground(new java.awt.Color(0, 0, 0));
        optionD.setColumns(20);
        optionD.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        optionD.setForeground(new java.awt.Color(255, 255, 255));
        optionD.setRows(5);
        jScrollPane1.setViewportView(optionD);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 430, 460, 40);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Answer :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 500, 110, 30);

        question.setBackground(new java.awt.Color(0, 0, 0));
        question.setColumns(20);
        question.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        question.setForeground(new java.awt.Color(255, 255, 255));
        question.setRows(5);
        jScrollPane2.setViewportView(question);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(160, 80, 800, 90);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("(A)");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 190, 20, 30);

        optionA.setBackground(new java.awt.Color(0, 0, 0));
        optionA.setColumns(20);
        optionA.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        optionA.setForeground(new java.awt.Color(255, 255, 255));
        optionA.setRows(5);
        jScrollPane3.setViewportView(optionA);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(60, 190, 460, 40);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("(B)");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 270, 20, 30);

        optionB.setBackground(new java.awt.Color(0, 0, 0));
        optionB.setColumns(20);
        optionB.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        optionB.setForeground(new java.awt.Color(255, 255, 255));
        optionB.setRows(5);
        jScrollPane4.setViewportView(optionB);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(60, 270, 460, 40);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("(C)");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 350, 20, 30);

        optionC.setBackground(new java.awt.Color(0, 0, 0));
        optionC.setColumns(20);
        optionC.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        optionC.setForeground(new java.awt.Color(255, 255, 255));
        optionC.setRows(5);
        jScrollPane5.setViewportView(optionC);

        jPanel1.add(jScrollPane5);
        jScrollPane5.setBounds(60, 350, 460, 40);

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back);
        back.setBounds(60, 560, 160, 50);

        submit.setBackground(new java.awt.Color(0, 153, 0));
        submit.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(260, 560, 170, 50);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("QUESTIONS :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 40, 160, 30);

        answer.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        answer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "a", "b", "c", "d" }));
        jPanel1.add(answer);
        answer.setBounds(200, 500, 360, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizapp/ui/admin/9db2c0dbc29802cdd540db19a0da8e8b.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -180, 1170, 840);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1174, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        new AdminDashboard().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        boolean isAdded = questionService.addQuestion(new Question(question.getText(), optionA.getText(), optionB.getText(), optionC.getText(), optionD.getText(), answer.getSelectedItem().toString()));
        if (isAdded) {
            JOptionPane.showMessageDialog(null, "Question addition successful!");
        } else {
            JOptionPane.showMessageDialog(null, "Question addition failed!");
        }
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> answer;
    private javax.swing.JButton back;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea optionA;
    private javax.swing.JTextArea optionB;
    private javax.swing.JTextArea optionC;
    private javax.swing.JTextArea optionD;
    private javax.swing.JTextArea question;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
